version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: foreman start -f Procfile.development
    environment:
      - DATABASE_HOST=db
    volumes:
      - .:/app
    ports:
      - "1080:1080"
      - "3000:3000"
    depends_on:
      - db
